In [52]:
import pandas as pd

In [53]:
protiens_3 = pd.read_excel("../Original Spreadsheets/Adam_Proteomics_3.xlsx", sheet_name=0)
protiens_identifiers_3 = pd.DataFrame([["Q331K_M1","cortex", "TDP43TurboID", "1.5"],
                                        ["Q331K_M2","cortex", "TDP43TurboID", "1.5"],
                                        ["WT_M3","cortex", "TDP43TurboID", "1.5"],
                                        ["WT_M4","cortex", "TDP43TurboID", "1.5"]], 
                                    columns=["Sample_Name", "Fraction", "Virus", "Biotin"])

In [54]:
protiens_identifiers_3

  Sample_Name Fraction         Virus Biotin
0    Q331K_M1   cortex  TDP43TurboID    1.5
1    Q331K_M2   cortex  TDP43TurboID    1.5
2       WT_M3   cortex  TDP43TurboID    1.5
3       WT_M4   cortex  TDP43TurboID    1.5

In [55]:
protiens_3.head()

,Protein Group,Protein Ids,Protein Names,Genes,First Protein Description,Peptides,Q331K_M1,Q331K_M2,WT_M3,WT_M4,ttest_p_value,ttest_p_value_adjusted,Q331K-WT log2FC
0,Q921F2,Q921F2;A0A087WP57;A0A087WR97;A0A087WRZ5;A0A087...,TADBP_MOUSE,Tardbp,TAR DNA-binding protein 43,14,21257300.0,16359000.0,2787610.0,15447600.0,0.351160,0.714781,1.506780
1,A0A0A6YY91,A0A0A6YY91,A0A0A6YY91_MOUSE,Ncam1,"Isoform of P13595, Neural cell adhesion molecu...",2,625371.0,1273580.0,77989.7,520406.0,0.279680,0.714781,2.147265
2,A0A0R4J0I1,A0A0R4J0I1,A0A0R4J0I1_MOUSE,Serpina3k,"Isoform of P07759, Serine protease inhibitor A3K",2,79336.8,133332.0,141980.0,166668.0,0.276568,0.714781,-0.580795
3,A0A140LHB7,A0A140LHB7,A0A140LHB7_MOUSE,Efl1,"Isoform of Q8C0D5, Tr-type G domain-containing...",1,6103260.0,5084280.0,5314530.0,4974480.0,0.496252,0.714781,0.115570
4,A0A1W2P872;D3YVV7,D3YVV7;A0A1W2P872,A0A1W2P872_MOUSE;D3YVV7_MOUSE,Nova2,"Isoform of D3YVV7, NOVA alternative-splicing r...",9,555183.0,454585.0,32248.8,629960.0,0.486723,0.714781,1.817465

In [56]:
print(protiens_3.columns)
protiens_3.info()

Index(['Protein Group', 'Protein Ids', 'Protein Names', 'Genes',
       'First Protein Description', 'Peptides', 'Q331K_M1', 'Q331K_M2',
       'WT_M3', 'WT_M4', 'ttest_p_value', 'ttest_p_value_adjusted',
       'Q331K-WT log2FC'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 707 entries, 0 to 706
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Protein Group              707 non-null    object
 1   Protein Ids                707 non-null    object
 2   Protein Names              707 non-null    object
 3   Genes                      707 non-null    object
 4   First Protein Description  707 non-null    object
 5   Peptides                   707 non-null    int64
 6   Q331K_M1                   644 non-null    float64
 7   Q331K_M2                   667 non-null    float64
 8   WT_M3                      442 non-null    float64
 9   WT_M4                      616 non-null    float64
 10  ttest_p_value              624 non-null    float64
 11  ttest_p_value_adjusted     624 non-null    float64
 12  Q331K-WT log2FC            624 non-null    float64
dtypes: float64(7), int64(1), object(5)
memory usage: 71.9+ KB

In [57]:
protiens_3 = protiens_3[['Protein Group', 'Protein Ids', 'Protein Names', 'Genes',
                        'First Protein Description', 'Peptides', 'Q331K_M1', 'Q331K_M2',
                        'WT_M3', 'WT_M4']]
protiens_3 = protiens_3.fillna(0)
protiens_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 707 entries, 0 to 706
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Protein Group              707 non-null    object
 1   Protein Ids                707 non-null    object
 2   Protein Names              707 non-null    object
 3   Genes                      707 non-null    object
 4   First Protein Description  707 non-null    object
 5   Peptides                   707 non-null    int64
 6   Q331K_M1                   707 non-null    float64
 7   Q331K_M2                   707 non-null    float64
 8   WT_M3                      707 non-null    float64
 9   WT_M4                      707 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 55.4+ KB

In [58]:
protiens_3 = protiens_3.rename(columns= {"Protein Names":"Protein_Names",
                                     "Protein Group":"Protein_Group",
                                     "Protein Ids":"Protein_Ids",
                                     "First Protein Description":"First_Protein_Description"})
protiens_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 707 entries, 0 to 706
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Protein_Group              707 non-null    object
 1   Protein_Ids                707 non-null    object
 2   Protein_Names              707 non-null    object
 3   Genes                      707 non-null    object
 4   First_Protein_Description  707 non-null    object
 5   Peptides                   707 non-null    int64
 6   Q331K_M1                   707 non-null    float64
 7   Q331K_M2                   707 non-null    float64
 8   WT_M3                      707 non-null    float64
 9   WT_M4                      707 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 55.4+ KB

In [59]:
protiens_3.to_csv("proteins_denormalized_3.csv")
protiens_identifiers_3.to_csv("proteins_identifiers_denormalized_3.csv")

In [60]:
# create mouse to protiens hit table based on protiens_2
protein_mouse_1 = protiens_3[["Protein_Names", "Q331K_M1"]]
protein_mouse_2 = protiens_3[["Protein_Names", "Q331K_M2"]]
protein_mouse_3 = protiens_3[["Protein_Names", "WT_M3"]]
protein_mouse_4 = protiens_3[["Protein_Names", "WT_M4"]]

protein_mouse_1["Sample_Name"] = "Q331K_M1"
protein_mouse_2["Sample_Name"] = "Q331K_M2"
protein_mouse_3["Sample_Name"] = "WT_M3"
protein_mouse_4["Sample_Name"] = "WT_M4"

protein_mouse_1 = protein_mouse_1.rename(columns = {"Q331K_M1":"Hits"})
protein_mouse_2 = protein_mouse_2.rename(columns = {"Q331K_M2":"Hits"})
protein_mouse_3 = protein_mouse_3.rename(columns = {"WT_M3":"Hits"})
protein_mouse_4 = protein_mouse_4.rename(columns = {"WT_M4":"Hits"})

union_dfs = pd.concat([protein_mouse_1, protein_mouse_2, protein_mouse_3, protein_mouse_4], ignore_index=True)

union_dfs = union_dfs[["Protein_Names", "Sample_Name", "Hits"]]
union_dfs.head()

C:\Users\Adam Brewer\AppData\Local\Temp\ipykernel_7728\3496315065.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  protein_mouse_1["Sample_Name"] = "Q331K_M1"
C:\Users\Adam Brewer\AppData\Local\Temp\ipykernel_7728\3496315065.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  protein_mouse_2["Sample_Name"] = "Q331K_M2"
C:\Users\Adam Brewer\AppData\Local\Temp\ipykernel_7728\3496315065.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  protein_mouse_3["Sample_Name"] = "WT_M3"
C:\Users\Adam Brewer\AppData\Local\Temp\ipykernel_7728\3496315065.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  protein_mouse_4["Sample_Name"] = "WT_M4"

                   Protein_Names Sample_Name        Hits
0                    TADBP_MOUSE    Q331K_M1  21257300.0
1               A0A0A6YY91_MOUSE    Q331K_M1    625371.0
2               A0A0R4J0I1_MOUSE    Q331K_M1     79336.8
3               A0A140LHB7_MOUSE    Q331K_M1   6103260.0
4  A0A1W2P872_MOUSE;D3YVV7_MOUSE    Q331K_M1    555183.0

In [61]:
union_dfs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2828 entries, 0 to 2827
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Protein_Names  2828 non-null   object
 1   Sample_Name    2828 non-null   object
 2   Hits           2828 non-null   float64
dtypes: float64(1), object(2)
memory usage: 66.4+ KB

In [62]:
union_dfs.to_csv("mouse_by_protein_3.csv")